apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-ai
spec:
  selector:
    matchLabels:
      app: local-ai
  replicas: 1
  template:
    metadata:
      name: local-ai
      labels:
        app: local-ai
    spec:
      initContainers:
        - name: download-model
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              url="https://gpt4all.io/models/ggml-gpt4all-l13b-snoozy.bin"
              model="ggml-gpt4all-l13b-snoozy"
              wget "${url}" -O "/models/${model}"
          volumeMounts:
            - mountPath: /models
              name: models

      containers:
        - name: local-ai
          image: quay.io/go-skynet/local-ai:master
          env:
            - name: THREADS
              value: "6"
            - name: CONTEXT_SIZE
              value: "512"
            - name: MODELS_PATH
              value: /models
          volumeMounts:
            - name: models
              mountPath: /models
            - name: template
              mountPath: /models/ggml-gpt4all-l13b-snoozy.tmpl
              subPath: model.tmpl
              readOnly: true
      volumes:
        - name: models
          emptyDir: {}
        - name: template
          configMap:
            name: local-ai
            items:
              - key: model.tmpl
                path: model.tmpl